CREATE SEQUENCE usuario_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS SEQUENCE usuario_id_seq PRIMARY KEY,nome varchar(100) NOT NULL,
  usuario varchar(10) NOT NULL,
  senha varchar(8) NOT NULL,
  sexo varchar(9) NOT NULL,
  raca varchar(15) NOT NULL,
  reino varchar(15) NOT NULL
)
;